### ISSUE TITLE
Customising snapshot transactions & pre/post snapshots

### ISSUE THREAD

**Issue by Rend0e** [pwernicki/timeshift-autosnap-dnf#2]
Hello, is there a way to disable post snapshots in particular?

Also would it be possible to customize the snapshot transactions etc disable snapshots on installing and removing packages to have it only snapshot on DNF update transactions.

Thanks,

**Comment by pwernicki** [comment]
Hello, 
I added options You requested. Please pull changes from repo, check and let me know.

Beset Regards

**Comment by Rend0e** [comment]
Hi, tested different settings and everything works well except setting `pre_snap` to `False` has no effect where it still creates pre snapshots although it doesn't really make sense to turn off pre snapshots anyways.

Also only post snapshots seems to remove older snapshots so setting `post_snap` to `False` will prevent older snapshots from being removed thereby the number of snapshots will go over `max_backups` when only having pre snapshots.

Thanks!

**Comment by pwernicki** [comment]
Hello, 
You're right, the pre_snap to False doesn't make any sense. I deleted this option and fix snapshots deletions.
Thanks for pointing this bugs out.

**Comment by Rend0e** [comment]
Hi, I've tested it again and everything works!

Thanks!

**Comment by pwernicki** [comment]
Hello,
I'm glad to hear that!

Best Regards
